# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-11 04:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bns_info', '0002_auto_20170513_0517'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dungeon',
            old_name='dtype',
            new_name='dType',
        ),
        migrations.RenameField(
            model_name='dungeon',
            old_name='namednum',
            new_name='namedNum',
        ),
        migrations.RenameField(
            model_name='tactics',
            old_name='cname',
            new_name='cName',
        ),
        migrations.RenameField(
            model_name='tactics',
            old_name='dtype',
            new_name='dType',
        ),
        migrations.RenameField(
            model_name='tactics',
            old_name='namednum',
            new_name='namedNum',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='dtype',
            new_name='dType',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='teamleader',
            new_name='teamLeader',
        ),
        migrations.RemoveField(
            model_name='character',
            name='teamnum',
        ),
        migrations.RemoveField(
            model_name='tactics',
            name='teamnum',
        ),
        migrations.RemoveField(
            model_name='team',
            name='teamnum',
        ),
        migrations.AddField(
            model_name='character',
            name='teamNum',
            field=models.TextField(blank=True, db_column='teamNum', null=True),
        ),
        migrations.AddField(
            model_name='tactics',
            name='teamNum',
            field=models.TextField(blank=True, db_column='teamNum', null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='teamNum',
            field=models.TextField(blank=True, db_column='teamNum', null=True),
        ),
    ]
