# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-12 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('teamnum', models.IntegerField(blank=True, db_column='teamNum', null=True)),
                ('ident', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Character',
            },
        ),
        migrations.CreateModel(
            name='Dungeon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtype', models.IntegerField(blank=True, db_column='dType', null=True)),
                ('namednum', models.IntegerField(blank=True, db_column='namedNum', null=True)),
            ],
            options={
                'db_table': 'Dungeon',
            },
        ),
        migrations.CreateModel(
            name='Tactics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamnum', models.IntegerField(blank=True, db_column='teamNum', null=True)),
                ('role', models.IntegerField(blank=True, null=True)),
                ('cname', models.TextField(blank=True, db_column='cName', null=True)),
                ('dtype', models.IntegerField(blank=True, db_column='dType', null=True)),
                ('ident', models.IntegerField(blank=True, null=True)),
                ('namednum', models.IntegerField(blank=True, db_column='namedNum', null=True)),
            ],
            options={
                'db_table': 'Tactics',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamleader', models.TextField(blank=True, db_column='teamLeader', null=True)),
                ('teamnum', models.IntegerField(blank=True, db_column='teamNum', null=True)),
                ('dtype', models.IntegerField(blank=True, db_column='dType', null=True)),
            ],
            options={
                'db_table': 'Team',
            },
        ),
    ]
