# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-12 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bns_info', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='ident',
        ),
        migrations.RemoveField(
            model_name='tactics',
            name='ident',
        ),
        migrations.AlterField(
            model_name='character',
            name='id',
            field=models.IntegerField(blank=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tactics',
            name='id',
            field=models.IntegerField(blank=True, primary_key=True, serialize=False),
        ),
    ]
