# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-12 04:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bns_info', '0003_auto_20170611_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tactics',
            name='role',
            field=models.TextField(blank=True, null=True),
        ),
    ]
